server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testAI
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: testAI
  ai:
    openai:
      api-key:
      chat:
        model: gpt-5.3-codex
